d/rules.real: Unset KBUILD_HOSTCFLAGS etc. instead of overriding to be empty
The upstream Makefile tries to add some flags to KBUILD_HOSTCFLAGS,
and now fails to build anything if we override it to be empty:

    .../scripts/kconfig/util.c:11:10: fatal error: hashtable.h: No such file or directory
       11 | #include <hashtable.h>
          |          ^~~~~~~~~~~~~
    compilation terminated.

Instead of overriding these flags variables to be empty, unset them in
the environment.