topconfig disable sis190
disable temporarly sis190 due to build breakage:
drivers/net/sis190.c:329: error: sis190_pci_tbl causes a section type conflict
make[5]: *** [drivers/net/sis190.o] Error 1

svn path=/dists/trunk/linux-2.6/; revision=10272